services:
  photo-note-api:
    build:
      context: ./photo-note-api
      dockerfile: Dockerfile
    networks:
      - spring-s3-sample-jjug-ccc-2025
    ports:
      - 8080:8080
    healthcheck:
      test: "curl -f http://localhost:8080/actuator/health || exit 1"
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s
    depends_on:
      mysql:
        condition: service_healthy
      localstack:
        condition: service_healthy
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_KEY: test123456
      AWS_REGION: ap-northeast-1
      AWS_S3_ENDPOINT: http://localstack:4566/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/jjug
      SPRING_DATASOURCE_USERNAME: gara
      SPRING_DATASOURCE_PASSWORD: password

  mysql:
    image: mysql:latest
    environment:
      MYSQL_USER: gara
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: jjug
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - spring-s3-sample-jjug-ccc-2025
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s

  localstack:
    image: localstack/localstack:s3-latest
    networks:
      - spring-s3-sample-jjug-ccc-2025
    ports:
      - 4566:4566
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4566/_localstack/health" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test123456
      DEBUG: 1

networks:
  spring-s3-sample-jjug-ccc-2025:
    driver: bridge
