services:
  photo-note-api:
    build:
      context: ./photo-note-api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    healthcheck:
      test: "curl -f http://localhost:8080/actuator/health || exit 1"
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s
    depends_on:
      mysql:
        condition: service_healthy
      localstack:
        condition: service_healthy
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_KEY: test
      AWS_REGION: ap-northeast-1
      AWS_S3_ENDPOINT: http://localhost.localstack.cloud:4566/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/jjug
      SPRING_DATASOURCE_USERNAME: gara
      SPRING_DATASOURCE_PASSWORD: password

  photo-note-frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 3000:80
    depends_on:
      photo-note-api:
        condition: service_healthy
    environment:
      REACT_APP_API_URL: http://photo-note-api:8080

  mysql:
    image: mysql:latest
    environment:
      MYSQL_USER: gara
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: jjug
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s

  localstack:
    image: localstack/localstack-pro:latest
    networks:
      default:
        aliases:
          - localhost.localstack.cloud
    ports:
      - 4566:4566
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - ./init_s3.sh:/etc/localstack/init/ready.d/init_s3.sh
    environment:
      DEBUG: 1
      S3_SKIP_SIGNATURE_VALIDATION: 0
      LOCALSTACK_AUTH_TOKEN: ${LOCALSTACK_AUTH_TOKEN}
