services:
  photo-note-api:
    build:
      context: ./photo-note-api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    healthcheck:
      test: "curl -f http://localhost:8080/actuator/health || exit 1"
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s
    depends_on:
      mysql:
        condition: service_healthy
      garage:
        condition: service_healthy
    environment:
      AWS_ACCESS_KEY_ID: testtest
      AWS_SECRET_KEY: testtesttesttest
      AWS_REGION: ap-northeast-1
      AWS_S3_ENDPOINT: http://s3.localhost:3900/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/jjug
      SPRING_DATASOURCE_USERNAME: gara
      SPRING_DATASOURCE_PASSWORD: password

  photo-note-frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 3000:80
    depends_on:
      photo-note-api:
        condition: service_healthy
    environment:
      REACT_APP_API_URL: http://photo-note-api:8080

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: gara
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: jjug
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s

  garage:
    build:
      context: ./garage
      dockerfile: Dockerfile
    networks:
      default:
        aliases:
          - s3.localhost
          - jjug-ccc-2025.s3.localhost
    ports:
      - 3900:3900
    healthcheck:
      test: ["CMD", "/garage", "status"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s
