services:
  photo-note-frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    networks:
      - spring-s3-sample-jjug-ccc-2025
    ports:
      - 3000:80
    depends_on:
      photo-note-api:
        condition: service_healthy
    environment:
      REACT_APP_API_URL: http://photo-note-api:8080

  photo-note-api:
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_KEY:
      AWS_REGION: ap-northeast-1
      AWS_S3_ENDPOINT:
