name: CI Pipeline

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Mise install
        uses: jdx/mise-action@v4
      - name: Run unit test
        working-directory: photo-note-api
        env:
          LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}
        run: mvn clean test

  build_and_upload_jar_file:
    needs: unit_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Mise install
        uses: jdx/mise-action@v4
      - name: Build jar file
        working-directory: photo-note-api
        run: mvn clean package -Dmaven.test.skip=true
      - name: Upload Dockerfile and jar file
        uses: actions/upload-artifact@v7
        with:
          name: jar-and-Dockerfile
          path: |
            photo-note-api/Dockerfile
            photo-note-api/target/photo-note-api-1.0-SNAPSHOT.jar

  integration_test:
    needs: build_and_upload_jar_file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: setup docker-compose
        uses: KengoTODA/actions-setup-docker-compose@v1.2.4
        with:
          version: "2.33.1"
      - name: Mise install
        uses: jdx/mise-action@v4
      - name: Download Dockerfile and jar file
        uses: actions/download-artifact@v8
        with:
          name: jar-and-Dockerfile
          path: photo-note-api
      - name: Run integration test
        working-directory: integration-test
        env:
          LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}
        run: mvn clean verify
